namespace ThirdCppWinRTAppv2
{
    [default_interface]
    runtimeclass CalcButton : Microsoft.UI.Xaml.Controls.UserControl
    {
        CalcButton();
        String TopText;
        String BottomText;

		event Windows.Foundation.TypedEventHandler<CalcButton, Microsoft.UI.Xaml.RoutedEventArgs> CalcButtonClicked;
    }
}
